const BLOG='martimcesar';
const FEED=`https://${BLOG}.blogspot.com/feeds/posts/default`;
const PAGE_SIZE=150, VIEW=18;
const state={posts:[],filtered:[],rendered:0,search:'',year:'all',type:'all'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const THEMES={amor:['Amor','#3e1724','#8b4257','#d6a6a7'],noite:['Noite','#0e1631','#27346a','#91a2d9'],natureza:['Natureza','#14261b','#35523b','#90aa7d'],agua:['Água','#112630','#245b72','#83c0d6'],memoria:['Memória','#2b2018','#6a4a36','#d6b58a'],musica:['Música','#22152d','#5f3572','#d39fda'],fronteira:['Fronteira','#2b1710','#7a4d2b','#d5a26b'],cidade:['Cidade','#171717','#434343','#b8b8b8'],dor:['Dor & sombra','#171317','#3d3240','#8e7d95'],palavra:['Palavra','#231a16','#5a4031','#cfab84']};
function jsonp(url,cb){return new Promise((resolve,reject)=>{const s=document.createElement('script');const t=setTimeout(()=>done(new Error('timeout')),18000);function done(err,data){clearTimeout(t);delete window[cb];s.remove();err?reject(err):resolve(data)}window[cb]=d=>done(null,d);s.onerror=()=>done(new Error('feed'));s.src=`${url}${url.includes('?')?'&':'?'}alt=json-in-script&callback=${cb}`;document.head.appendChild(s)})}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function date(d){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'long',year:'numeric'}).format(d)}
function excerpt(t,n=180){t=(t||'').replace(/Postado por.*$/i,'').replace(/\s+/g,' ').trim();if(!t)return'Uma leitura preservada no acervo Poemarte.';return t.length>n?t.slice(0,n).replace(/\s+\S*$/,'')+'…':t}
function normImg(u=''){return String(u).replace(/^http:/,'https:').replace(/\/s\d+(-[a-z]\d+)?\//gi,'/s1600/').replace(/=w\d+-h\d+(-[a-z]\d+)?/gi,'=s1600').replace(/=s\d+(-c)?/gi,'=s1600')}
function ytThumb(h=''){const m=h.match(/(?:youtube\.com\/(?:embed\/|watch\?v=)|youtu\.be\/)([\w-]{6,})/i);return m?`https://i.ytimg.com/vi/${m[1]}/hqdefault.jpg`:''}
function themeOf(text,title){const s=`${title} ${text}`.toLowerCase();const r=[['musica',/(can[cç][aã]o|m[uú]sica|melodia|canto|viol[aã]o|festival|compositor|samba|valsa)/],['amor',/(amor|amar|paix[aã]o|beijo|cora[cç][aã]o|saudade|abra[cç]o|desejo)/],['agua',/(mar|rio|chuva|onda|[áa]gua|lago|barco|porto|oceano)/],['natureza',/(flor|terra|vento|sol|lua|estrela|p[aá]ssaro|campo|[aá]rvore|folha|serra)/],['fronteira',/(fronteira|estrada|caminho|viagem|travessia|uruguai|argentina|brasil|ponte)/],['cidade',/(cidade|rua|janela|pra[cç]a|esquina|bairro|povo|jornal)/],['dor',/(morte|dor|sombra|solid[aã]o|sil[eê]ncio|medo|luto|triste|aus[eê]ncia)/],['memoria',/(mem[oó]ria|lembran[cç]a|tempo|ontem|inf[aâ]ncia|passado|retrato|hist[oó]ria)/]];for(const [k,x] of r)if(x.test(s))return k;return'palavra'}
function fallback(k){const [label,a,b,c]=THEMES[k]||THEMES.palavra;const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 1000"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="${a}"/><stop offset=".52" stop-color="${b}"/><stop offset="1" stop-color="${c}"/></linearGradient><radialGradient id="r"><stop stop-color="#fff" stop-opacity=".17"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient></defs><rect width="800" height="1000" fill="url(#g)"/><circle cx="615" cy="225" r="270" fill="url(#r)"/><circle cx="150" cy="850" r="220" fill="#fff" opacity=".04"/><path d="M120 720 Q280 480 420 590 T700 330" fill="none" stroke="#fff" stroke-opacity=".19" stroke-width="12"/><path d="M90 780 Q310 610 700 650" fill="none" stroke="#fff" stroke-opacity=".09" stroke-width="4"/><rect x="42" y="42" width="716" height="916" rx="38" fill="none" stroke="#fff" stroke-opacity=".14" stroke-width="2"/></svg>`;return`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`}
function normalize(e){const link=(e.link||[]).find(x=>x.rel==='alternate');const html=e.content?.$t||e.summary?.$t||'';const box=document.createElement('div');box.innerHTML=html;box.querySelectorAll('script,style,noscript').forEach(x=>x.remove());const title=(e.title?.$t||'Sem título').trim();const text=(box.textContent||'').replace(/\s+/g,' ').trim();const published=new Date(e.published?.$t||e.updated?.$t||Date.now());const cats=(e.category||[]).map(x=>x.term).filter(Boolean);const type=/poema|poesia|verso|soneto|copla|poetas?|cantiga|canção/i.test(`${title} ${cats.join(' ')} ${text.slice(0,180)}`)?'poetry':'other';const key=themeOf(text,title);const image=normImg(box.querySelector('img')?.src||e.media$thumbnail?.url||'');return{id:e.id?.$t||link?.href||`${published.getTime()}-${title}`,title,url:link?.href||'#',content:html,text,excerpt:excerpt(text),published,year:published.getFullYear(),type,key,image,videoThumb:ytThumb(html),cover:{src:image||ytThumb(html)||fallback(key),fallback:fallback(key),theme:{label:THEMES[key][0]}}}}
async function load(){const seen=new Set();for(let y=2018;y>=2010;y--){let start=1;for(let p=0;p<4;p++){const min=encodeURIComponent(`${y}-01-01T00:00:00-03:00`),max=encodeURIComponent(`${y+1}-01-01T00:00:00-03:00`),cb=`pf_${y}_${p}_${Date.now()}`;const data=await jsonp(`${FEED}?max-results=${PAGE_SIZE}&start-index=${start}&published-min=${min}&published-max=${max}`,cb);const es=data?.feed?.entry||[];for(const e of es){const post=normalize(e);if(!seen.has(post.id)){seen.add(post.id);state.posts.push(post)}}if(es.length<PAGE_SIZE)break;start+=es.length}}state.posts.sort((a,b)=>b.published-a.published)}
function counts(){return state.posts.reduce((a,p)=>(a[p.year]=(a[p.year]||0)+1,a),{})}
function setup(){const c=counts(),years=Object.keys(c).map(Number).sort((a,b)=>b-a);$('#yearFilter').innerHTML='<option value="all">Todos os anos</option>'+years.map(y=>`<option value="${y}">${y} · ${c[y]}</option>`).join('');$('#timeline').innerHTML=`<button class="active" data-year="all"><span>Todo o arquivo</span><small>${state.posts.length}</small></button>`+years.map(y=>`<button data-year="${y}"><span>${y}</span><small>${c[y]}</small></button>`).join('');const pc=state.posts.filter(p=>p.type==='poetry').length;$('#statPosts').textContent=state.posts.length||'815+';$('#statPoetry').textContent=pc;$('#heroPoetryCount').textContent=pc;$('#statYears').textContent=years.length;$('#statLatest').textContent=years[0]||'—'}
function filter(reset=true){const q=state.search.toLowerCase().trim();state.filtered=state.posts.filter(p=>(!q||`${p.title} ${p.text}`.toLowerCase().includes(q))&&(state.year==='all'||String(p.year)===String(state.year))&&(state.type==='all'||p.type===state.type));if(reset)state.rendered=0;render(reset)}
function media(img,p){img.src=p.cover.src;img.alt=`Imagem relacionada a ${p.title}`;img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>{if(img.src!==p.cover.fallback)img.src=p.cover.fallback}}
function card(p){const a=document.createElement('article');a.className='post-card';a.tabIndex=0;a.innerHTML=`<div class="post-media"><img><div class="post-tags"><span class="chip"><strong>${esc(p.cover.theme.label)}</strong></span><span class="chip">${p.type==='poetry'?'Poesia':'Arquivo'}</span></div></div><div class="post-body"><div class="post-meta"><span>${esc(date(p.published))}</span><span>${p.year}</span></div><h3 class="post-title">${esc(p.title)}</h3><p class="post-excerpt">${esc(p.excerpt)}</p><div class="post-footer"><span>${esc(p.cover.theme.label)}</span><span class="arrow">↗</span></div></div>`;media(a.querySelector('img'),p);a.onclick=()=>openReader(p);a.onkeydown=e=>{if(e.key==='Enter')openReader(p)};return a}
function render(reset=false){const g=$('#postsGrid');if(reset)g.innerHTML='';const next=state.filtered.slice(state.rendered,state.rendered+VIEW);if(!next.length&&!state.rendered)g.innerHTML='<article class="post-card empty-card" style="grid-column:1/-1;padding:32px;min-height:200px;justify-content:center"><h3 class="post-title">Nenhuma publicação encontrada.</h3><p class="post-excerpt">Tente outra palavra, ano ou tipo de conteúdo.</p></article>';else next.forEach(p=>g.appendChild(card(p)));state.rendered+=next.length;$('#loadMore').hidden=state.rendered>=state.filtered.length}
function featured(){const p=state.posts.find(x=>x.type==='poetry'&&(x.image||x.videoThumb)&&x.text.length>220)||state.posts.find(x=>x.type==='poetry'&&x.text.length>220)||state.posts[0];if(!p)return;const a=$('#featuredPost');a.innerHTML=`<div class="featured-visual"><img><div class="featured-caption"><span class="chip"><strong>${esc(p.cover.theme.label)}</strong></span><span class="chip">${p.type==='poetry'?'Poema em destaque':'Arquivo em destaque'}</span></div></div><div class="featured-content"><span class="kicker">${esc(date(p.published).toUpperCase())}</span><h3>${esc(p.title)}</h3><p>${esc(excerpt(p.text,360))}</p><span class="read-link">Ler publicação completa →</span></div>`;media(a.querySelector('img'),p);a.onclick=()=>openReader(p)}
function clean(html=''){const t=document.createElement('template');t.innerHTML=html;t.content.querySelectorAll('script,style,noscript,form,input,button').forEach(x=>x.remove());t.content.querySelectorAll('*').forEach(x=>{[...x.attributes].forEach(a=>{if(/^on/i.test(a.name)||['width','height','data-original-height','data-original-width'].includes(a.name))x.removeAttribute(a.name);if(a.name==='style')x.removeAttribute('style')});if(x.tagName==='A'){x.target='_blank';x.rel='noopener'}if(x.tagName==='IMG'){x.src=normImg(x.src);x.loading='lazy';x.referrerPolicy='no-referrer'}if(x.tagName==='IFRAME'){x.loading='lazy';x.referrerPolicy='no-referrer'}});return t.innerHTML}
function openReader(p){$('#readerDate').textContent=date(p.published);$('#readerCategory').textContent=`${p.cover.theme.label} · ${p.type==='poetry'?'Poesia':'Arquivo'}`;$('#readerTitle').textContent=p.title;$('#readerContent').innerHTML=clean(p.content||`<p>${esc(p.text)}</p>`);$('#readerLead').innerHTML='<img>';media($('#readerLead img'),p);const d=$('#reader');d.showModal();d.querySelector('.reader-scroll').scrollTop=0}
function search(q=''){const n=q.toLowerCase().trim(),list=(n?state.posts.filter(p=>`${p.title} ${p.text}`.toLowerCase().includes(n)):state.posts).slice(0,12),h=$('#modalSearchResults');h.innerHTML='';list.forEach(p=>{const x=document.createElement('div');x.className='modal-result';x.innerHTML=`<div class="modal-thumb"><img></div><div class="modal-copy"><small>${esc(date(p.published).toUpperCase())} · ${esc(p.cover.theme.label)}</small><h4>${esc(p.title)}</h4><p>${esc(excerpt(p.text,110))}</p></div>`;media(x.querySelector('img'),p);x.onclick=()=>{$('#searchModal').close();openReader(p)};h.appendChild(x)})}
function random(){const pool=state.posts.filter(p=>p.type==='poetry'),p=pool[Math.floor(Math.random()*pool.length)]||state.posts[Math.floor(Math.random()*state.posts.length)];if(p)openReader(p)}
function sync(){$$('#timeline button').forEach(b=>b.classList.toggle('active',b.dataset.year===String(state.year)))}
function events(){$('#inlineSearch').oninput=e=>{state.search=e.target.value;filter()};$('#yearFilter').onchange=e=>{state.year=e.target.value;sync();filter()};$('#typeFilter').onchange=e=>{state.type=e.target.value;filter()};$('#loadMore').onclick=()=>render();$('#randomPoem').onclick=random;$('#closeReader').onclick=()=>$('#reader').close();$('#reader').onclick=e=>{if(e.target===$('#reader'))$('#reader').close()};$('#openSearch').onclick=()=>{search();$('#searchModal').showModal();setTimeout(()=>$('#modalSearchInput').focus(),50)};$('#closeSearch').onclick=()=>$('#searchModal').close();$('#searchModal').onclick=e=>{if(e.target===$('#searchModal'))$('#searchModal').close()};$('#modalSearchInput').oninput=e=>search(e.target.value);$('#timeline').onclick=e=>{const b=e.target.closest('button[data-year]');if(!b)return;state.year=b.dataset.year;$('#yearFilter').value=state.year;sync();filter();$('#arquivo').scrollIntoView({behavior:'smooth'})}}
async function init(){events();try{await load();$('#loadingState').hidden=true;setup();featured();filter();search()}catch(e){console.error(e);$('#loadingState').innerHTML='<span>Não foi possível carregar o acervo agora. Recarregue a página em alguns instantes.</span>';$('#statPosts').textContent='815+'}}
init();
